[version]
path = "src/geoquest/__version__.py"

[envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]

[envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/geoquest tests}"

[envs.default]
dependencies = [
  "httpx",
  "rich",
  "python-dotenv",
]

[envs.default.scripts]
run_main = "python ./src/resumebuilder/main.py"

[envs.dev]
template = "deafult"
skip-install = false
dependencies = [
  "ruff",
  "rich",
]

[build.targets.sdist]
exclude = [
  "/.github",
  "/docs",
]

[build.targets.wheel]
packages = ["src/geoquest"]